- name: Increment Semantic Version
  id: bump_version
  uses: christian-draeger/increment-semantic-version@1.0.2
  with:
    current-version: "1.5.19"
    version-fragment: "feature"
- name: Magical things are happening~~~~~~~~~~
  run: echo ${{ steps.bump_version.outputs.next-version }}
  