name: Create Tag

# Only run if the PR closed by merging to main
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  check_tags:
    name: Check Tags
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_tag: ${{ steps.tag_check.outputs.git_tag_name }}
    steps:
      - uses: actions/checkout@v2.4.0

      # Checks if the package.json version exists as a tag in GitHub
      # Will not push a currently existing tag
      - uses: dudo/tag_check@v1.0.0
        id: tag_check
        with:
          git_tag_prefix: v

  push_tag:
    runs-on: ubuntu-latest
    needs: check_tags
    steps:
      - name: Push Tag to GitHub
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ needs.check_tags.outputs.new_tag }}
          git_commit_sha: ${{ github.sha }}
