name: Push Tag

# Run if a commit is pushed to main or a PR is merged to main
on:
  push:
    branches: [dev]

jobs:
  get_package_version:
    name: Get Version from Package.json
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_tag: ${{ steps.tag_check.outputs.git_tag_name }}
    steps:
      - uses: actions/checkout@v2.4.0

      - name:  Automated Version Bump
        uses:  phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: main
          tag-prefix: v
          default: minor
          commit-message: 'CI: {{version}} [skip ci]'
          patch-wording:  'juhyehyeh'
