name: Create Tag
# 1. Upon PR merge, compare version in package.json vs latest GH tag.
# 2. Create a new tag if the version in the package.json is greater than the latest GH tag. If not, end the process
# 3. Push the tag.

# Only run if the PR closed by merging to main
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  get-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: gagle/package-version@v1.0.0
        id: package-version
      - uses: WyriHaximus/github-action-get-previous-tag@v1
        id: previous-tag

    outputs:
        VERSION: ${{ steps.package-version.outputs.version }} # Store the version from the package.json as an output variable
        TAG: ${{ steps.previous-tag.outputs.tag }} # Store the previous tag as an output variable

  create-and-push-tag:
    runs-on: ubuntu-latest
    needs: get-versions
    if: ${{ needs.get-versions.outputs.VERSION > needs.get-versions.outputs.TAG }} # This comparison might not be robust...
    steps:
      - name: Version is greater here, so let's party!
        run: echo "NEW_VERSION=${{ needs.get-versions.outputs.VERSION }}" >> $GITHUB_ENV

      - name: Create & push the tag (will take a few minutes to appear on GitHub) 
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.NEW_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
