name: Create Tag

# Only run if the PR closed by merging to main
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  push_tag:
    runs-on: ubuntu-latest
    steps:
      # Checks if the package.json version exists as a tag in GitHub
      # Will not push a currently existing tag
      - name: Push Tag to GitHub
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ needs.check_tags.outputs.new_tag }}
          git_commit_sha: ${{ github.sha }}
