name: Create Tag

# Only run if a commit is pushed to main (also includes PR's merged)
on:
  push:
    branches: [main]

jobs:
  get_package_version:
    name: Get Version from Package.json
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_tag: ${{ steps.tag_check.outputs.git_tag_name }}
    steps:
      - uses: actions/checkout@v2.4.0

      # Checks if the package.json version exists as a tag in GitHub
      # Will not push a currently existing tag
      # And returns the package.json version as output.new_tag
      - uses: dudo/tag_check@v1.0.0
        id: tag_check
        with:
          git_tag_prefix: v

  push_tag:
    name: Push Tag to GitHub
    runs-on: ubuntu-latest
    needs: get_package_version
    steps:
      - uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ needs.get_package_version.outputs.new_tag }}
          git_commit_sha: ${{ github.sha }}
