name: Bump Version and Push Tag

# Run if a commit is pushed to main or a PR is merged to main
on:
  push:
    branches: [main]

jobs:
  bump_and_dump:
    name: 'Auto Tagger: Bump and Tag'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.4.0

      - name:  Automated Version Bump
        uses:  phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: v
          commit-message: 'Bump to {{version}}'
          major-wording: MAJOR,bigmode
          minor-wording: feat,lezzgo
          patch-wording: patch,piza
