name: Shall I Release to Prod?
# 1. Upon PR merge, compare version in package.json vs latest GH tag.
# 2. Create a new tag if the version in the package.json is greater than the latest GH tag. If not, end the process
# 3. Push the tag.
# 4. Release to prod.

# on:
#   pull_request:
#     types: [closed]
#     branches: [main]

# Just for testing on this branch
on: push

env:
  VERSION: 0.0.0
  TAG: 0.0.0

jobs:
  get-versions:
    # Only run if the PR closed by merging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: gagle/package-version@v1.0.0
        id: package-version
      - uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: previous-tag

      - name: Read the version from the package.json and store it as the environment variable VERSION
        run: echo "VERSION=${{ steps.package-version.outputs.version }}" >> $GITHUB_ENV

      - name: Get previous tag and store it as the environment variable TAG
        run: echo "TAG=${{ steps.previous-tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Display the version and tag
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.TAG }}

  release-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Compare the versions
        if: ${{ env.VERSION > env.TAG }}
        run: echo version is greater
