name: Shall I Release to Prod?
# 1. Upon PR merge, compare version in package.json vs latest GH tag.
# 2. Create a new tag if the version in the package.json is greater than the latest GH tag. If not, end the process
# 3. Push the tag.
# 4. Release to prod.

# on:
#   pull_request:
#     types: [closed]
#     branches: [main]

# Just for testing on this branch
on: push

env:
  VERSION: 0.0.0
  TAG: 0.0.0

jobs:
  compare-versions:
    # Only run if the PR closed by merging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: gagle/package-version@v1.0.0
        id: package-version

      - name: Read the version from the package.json and store it as the environment variable VERSION
        run: echo "VERSION=${{ steps.package-version.outputs.version }}" >> $GITHUB_ENV

      # - name: Get the latest tag from the main branch
      #   id: latest-tag
      #   run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      # - name: Get the latest tag from the main branch
      #   id: latest-tag
      #   run: | 
      #     echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      #     echo "TAG=${{ steps.latest-tag.outputs.VERSION }}" >> $GITHUB_ENV

      - name: 'Get Previous Tag'
        id: previous-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        run: echo "TAG=${{ steps.previous-tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Display the version and tag
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.TAG }}
