name: Shall I Release to Prod?
# 1. Upon PR merge, compare version in package.json vs latest GH tag.
# 2. Create a new tag if the version in the package.json is greater than the latest GH tag. If not, end the process
# 3. Push the tag.
# 4. Release to prod.

# Only run if the PR closed by merging to main
# on:
#   pull_request:
#     types: [closed]
#     branches: [main]

# Just for testing on this branch
on: push

env:
  VERSION: 0.0.0
  TAG: 0.0.0

jobs:
  get-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: gagle/package-version@v1.0.0
        id: package-version
      - uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: previous-tag

      - name: Read the version from the package.json and store it as the environment variable VERSION
        run: echo "VERSION=${{ steps.package-version.outputs.version }}" >> $GITHUB_ENV

      - name: Get previous tag and store it as the environment variable TAG
        run: echo "TAG=${{ steps.previous-tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Display the version and tag
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.TAG }}
    
    outputs:
        A: ${{ steps.package-version.outputs.version }}
        B: ${{ steps.previous-tag.outputs.tag }}

  # share vars between jobs
  release:
    runs-on: ubuntu-latest
    needs: get-versions
    if: ${{ needs.get-versions.outputs.A > needs.get-versions.outputs.B }}
    steps:
      - name: Check
        run: echo version is greater here, so let's party!