name: Test Area

on: push

jobs:
  clean-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: bhowell2/github-substring-action@v1.0.0
        id: one
        with:
          value: v1.0.0
          index_of_str: v

    outputs:
      var1: "1.9.1"    # this is a smaller number
      var2: v1.10.0  # this string has a v and the bigger number
      cleaned: ${{ steps.one.outputs.substring }}

  positive-case:
    runs-on: ubuntu-latest
    needs: [clean-tag]
    if: ${{ needs.clean-tag.outputs.var1 > needs.clean-tag.outputs.cleaned }}
    steps:
      - name: Positive Pass?
        run: |
          echo var1: ${{ needs.clean-tag.outputs.var1 }}
          echo var2: ${{ needs.clean-tag.outputs.var2 }}
          echo cleaned: ${{ needs.clean-tag.outputs.cleaned }}
      
  negative-case:
    runs-on: ubuntu-latest
    needs: [clean-tag]
    if: ${{ needs.clean-tag.outputs.var1 < needs.clean-tag.outputs.cleaned }}
    steps:
      - name: Negative Pass?
        run: |
          echo var1: ${{ needs.clean-tag.outputs.var1 }}
          echo var2: ${{ needs.clean-tag.outputs.var2 }}
          echo cleaned: ${{ needs.clean-tag.outputs.cleaned }}
      
