name: Test Area

on: push

jobs:
  # clean-tag:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: bhowell2/github-substring-action@v1.0.0
  #       id: one
  #       with:
  #         value: v1.10.0 # this string has a v
  #         index_of_str: v

  #   outputs:
  #     var1: 1.11.0  # this is a bigger version
  #     cleaned: ${{ steps.one.outputs.substring }}

  # log-versions:
  #   runs-on: ubuntu-latest
  #   needs: [clean-tag]
  #   steps:
  #     - name: Get Versions
  #       run: |
  #           echo var1: ${{ needs.clean-tag.outputs.var1 }}
  #           echo cleaned: ${{ needs.clean-tag.outputs.cleaned }}
  #     - uses: jackbilestech/semver-compare@1.0.0
  #       with:
  #         head: ${{ needs.clean-tag.outputs.var1 }}
  #         base: ${{ needs.clean-tag.outputs.cleaned }}
  #         operator: '>'


  # positive-case:
  #   runs-on: ubuntu-latest
  #   needs: [clean-tag, log-versions]
  #   if: ${{ needs.clean-tag.outputs.var1 > needs.clean-tag.outputs.cleaned }} # this sucks
  #   steps:
  #     - name: Positive Pass?
  #       run: |
  #         echo ${{ needs.clean-tag.outputs.var1 }} is greater than ${{ needs.clean-tag.outputs.cleaned }}

  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
      - uses: dudo/tag_check@v1.0.0 # automatically checks the package.json version
        with:
          git_tag_prefix: v

  positive-case:
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Positive Pass?
        run: |
          echo It passes!!!
