name: Test Area

on: 
  push: 
    branches:
      - vnguyen/auto-tagger-and-auto-releaser

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
      - uses: dudo/tag_check@v1.0.0 # checks if the package.json version exists as a tag in GitHub
        with:
          git_tag_prefix: v

  positive-case:
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Positive Pass?
        run: |
          echo It passes!!!
