name: Test Area

on: push

jobs:
  clean-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: bhowell2/github-substring-action@v1.0.0
        id: one
        with:
          value: v1.0.0
          index_of_str: v

    outputs:
      var1: 1.10.0    # this is a bigger version
      var2: v1.9.0    # this string has a v
      cleaned: ${{ steps.one.outputs.substring }}

  positive-case:
    runs-on: ubuntu-latest
    needs: [clean-tag]
    steps:
      - name: Compare!
        uses: jackbilestech/semver-compare@1.0.0
        with:
          head: ${{ needs.clean-tag.outputs.var1 }} # feature branch
          base: ${{ needs.clean-tag.outputs.var2 }} # main
          operator: '>'
        run: |
          echo var1: ${{ needs.clean-tag.outputs.var1 }}
          echo var2: ${{ needs.clean-tag.outputs.var2 }}
          echo cleaned: ${{ needs.clean-tag.outputs.cleaned }}

      - name: Positive Pass?
        run: |
          echo var1: ${{ needs.clean-tag.outputs.var1 }}
          echo var2: ${{ needs.clean-tag.outputs.var2 }}
          echo cleaned: ${{ needs.clean-tag.outputs.cleaned }}
      
      
