name: Test Area

on: push

jobs:
  clean-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: bhowell2/github-substring-action@v1.0.0
        id: one
        with:
          value: v1.0.0
          index_of_str: v

    outputs:
      var1: 1.0.1   # this is a bigger number
      var2: v1.0.0  # this string has a v
      cleaned: ${{ steps.one.outputs.substring }}

  whatever-xD:
    runs-on: ubuntu-latest
    needs: [clean-tag]
    if: ${{ needs.clean-tag.outputs.var1 > needs.clean-tag.outputs.cleaned }}
    steps:
      - name: isobopbelbee
        run: echo WE DID ITTTTT!
      
