name: Test Area

on: push

# env:
#   var1: 1.0.1   # this is a bigger number
#   var2: v1.0.0  # this string has a v
#   var3: answer

jobs:
  clean-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: bhowell2/github-substring-action@v1.0.0
        id: one
        with:
          value: ${{ env.var2 }}
          index_of_str: v

    outputs:
      cleaned: ${{ steps.one.outputs.substring }}

  whatever-xD:
    runs-on: ubuntu-latest
    needs: [clean-tag]
    env:
      var1: 1.0.1   # this is a bigger number
      var2: v1.0.0  # this string has a v
      var3: ${{ needs.clean-tag.outputs.cleaned }}
    if: ${{ env.var1 > env.var3 }}
    steps:
      - name: isobopbelbee
        run: echo WE DID ITTTTT!
      
