name: Test Area

on: push

env:
  VAR1: 1.0.1   # this is a bigger number
  VAR2: v1.0.0  # this string has a v
  VAR3: answer

jobs:
  clean-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: bhowell2/github-substring-action@v1.0.0
        id: one
        with:
          value: ${{ env.VAR2 }}
          index_of_str: v

      - name: Try it out
        run: echo "VAR3=${{ steps.one.outputs.substring }}" >> $GITHUB_ENV # '1.0.0'

  whatever-xD:
    runs-on: ubuntu-latest
    needs: [clean-tag]
    if: ${{ env.VAR1 > env.VAR3 }}
    steps:
      - name: isobopbelbee
        run: echo WE DID ITTTTT!
      
