- name: Bump release version
  id: bump_version
  uses: christian-draeger/increment-semantic-version@1.0.1
  with:
    current-version: '2.11.7-alpha3'
    version-fragment: 'feature'
- name: Do something with your bumped release version
  run: echo ${{ steps.bump_version.outputs.next-version }}
  # should print 2.12.0